name: Flask Backend CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PR to 'main' branch

jobs:
  backend-ci:
    runs-on: ubuntu-latest  # Using Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest

    - name: Run SonarQube analysis
      uses: sonarsource/sonarcloud-action@v1  # Change to commit SHA if still failing
      with:
        organization: 'your-organization'  # Replace with your SonarCloud organization
        projectKey: 'flask-backend-repo'  # Replace with your SonarCloud project key
        token: ${{ secrets.SONAR_TOKEN }}

    - name: Run Snyk test
      run: |
        source venv/bin/activate
        snyk test --all-projects
