name: Flask Backend CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on PR to 'main' branch

jobs:
  backend-ci:
    runs-on: ubuntu-latest  # Choose the operating system for the CI runner (Ubuntu in this case)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out your code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.9'  # Choose the Python version you are using for the project

    - name: Install dependencies
      run: |
        python -m venv venv  # Create a virtual environment
        source venv/bin/activate  # Activate the virtual environment
        pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install dependencies from the requirements.txt file

    - name: Run tests
      run: |
        source venv/bin/activate  # Ensure the virtual environment is activated
        pytest  # Run the tests using pytest

    - name: Run SonarQube analysis
      uses: sonarsource/sonarcloud-action@v2  # Use the SonarCloud action to analyze the code
      with:
        organization: 'your-organization'  # Replace with your SonarCloud organization name
        projectKey: 'flask-backend-repo'  # Replace with your SonarCloud project key
        token: ${{ secrets.SONAR_TOKEN }}  # Ensure SONAR_TOKEN is added to GitHub Secrets
